export const statevalues = [
  {
    id: 'IN-JK',
    name: 'Jammu and Kashmir',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-WB',
    name: 'West Bengal',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-UT',
    name: 'Uttarakhand',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-UP',
    name: 'Uttar Pradesh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-TR',
    name: 'Tripura',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-TN',
    name: 'Tamil Nadu',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-PY',
    name: 'Puducherry',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-TG',
    name: 'Telangana',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-SK',
    name: 'Sikkim',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-RJ',
    name: 'Rajasthan',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-PB',
    name: 'Punjab',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-OR',
    name: 'Odisha',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-NL',
    name: 'Nagaland',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-MZ',
    name: 'Mizoram',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-MP',
    name: 'Madhya Pradesh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-MN',
    name: 'Manipur',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-ML',
    name: 'Meghalaya',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-MH',
    name: 'Maharashtra',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-LD',
    name: 'Lakshadweep',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-KL',
    name: 'Kerala',
    active: 200,
    recovered: 100,
    deceased: 50,
  },
  {
    id: 'IN-KA',
    name: 'Karnataka',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-LK',
    name: 'Ladakh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-JH',
    name: 'Jharkhand',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-HR',
    name: 'Haryana',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-HP',
    name: 'Himachal Pradesh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-GJ',
    name: 'Gujarat',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-GA',
    name: 'Goa',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-DN',
    name: '',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-DL',
    name: 'Delhi',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-DD',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-CT',
    name: 'Chhattisgarh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-AP',
    name: 'Andhra Pradesh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-AR',
    name: 'Arunachal Pradesh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-AS',
    name: 'Assam',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-BR',
    name: 'Bihar',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-CH',
    name: 'Chandigarh',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
  {
    id: 'IN-AN',
    name: 'Andaman and Nicobar Islands',
    active: 0,
    recovered: 0,
    deceased: 0,
  },
];
